// <auto-generated />
using System;
using Baitkm.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Baitkm.DAL.Migrations
{
    [DbContext(typeof(BaitkmDbContext))]
    [Migration("20200205130004_Add_GuestFk_in_PersonNotification")]
    partial class Add_GuestFk_in_PersonNotification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementFeatures.AnnouncementFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("FeatureType");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementReports.AnnouncementReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ReportAnnouncementStatus");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("AnnouncementReports");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Announcements.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("AnnouncementApprovedDay");

                    b.Property<DateTime>("AnnouncementChangedDay");

                    b.Property<int>("AnnouncementEstateType");

                    b.Property<int?>("AnnouncementRentType");

                    b.Property<int?>("AnnouncementResidentialType");

                    b.Property<int>("AnnouncementStatus");

                    b.Property<DateTime>("AnnouncementStatusLastDay");

                    b.Property<int>("AnnouncementType");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("BasePhoto");

                    b.Property<int>("BathroomCount");

                    b.Property<int>("BedroomCount");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<string>("DescriptionArabian");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsDraft");

                    b.Property<bool>("IsOtherPeriod");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Title");

                    b.Property<string>("TitleArabian");

                    b.Property<bool>("TopAnnouncement");

                    b.Property<DateTime>("TopAnnouncementDayFrom");

                    b.Property<DateTime>("TopAnnouncementDayTo");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.Property<int>("ViewsCount");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Attachments.AnnouncementPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("AnnouncementPhotoType");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Photo");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("AnnouncementPhoto");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Cities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int?>("SaveFilterId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("SaveFilterId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Configurations.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Key");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementCreatorId");

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("QuestionerId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementCreatorId");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("QuestionerId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConversationId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<long>("FileLength");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSeen");

                    b.Property<int>("MessageBodyType");

                    b.Property<string>("MessageText");

                    b.Property<int>("SenderId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("DeviceId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OsType");

                    b.Property<string>("Token");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourite");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.GuestFavourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestFavourites");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("SubscriptionsType");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestSubscriptions");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscriptionAreaAndLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaUnit");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Language");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.ToTable("GuestSubscriptionAreaAndLanguage");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.HomePageCoverImages.HomePageCoverImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsBase");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Photo");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("HomePageCoverImages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("NotificationType");

                    b.Property<string>("Title");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Notifications.NotificationTranslate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Language");

                    b.Property<int>("NotificationId");

                    b.Property<string>("Title");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationTranslate");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PersonNotifications.PersonNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int?>("GuestId");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSeen");

                    b.Property<int?>("NotificationId");

                    b.Property<int?>("PushNotificationId");

                    b.Property<int?>("SenderId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("GuestId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("PushNotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonNotifications");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Title");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("DeviceId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OsType");

                    b.Property<string>("Token");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("LoginProvider");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("UniqueIdentifier");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("SubscriptionsType");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("ForgotKey");

                    b.Property<int>("ForgotPasswordVerified");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsBanned");

                    b.Property<bool>("IsBlocked");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsLocal");

                    b.Property<int>("OsType");

                    b.Property<string>("Phone");

                    b.Property<string>("PhoneCode");

                    b.Property<string>("ProfilePhoto");

                    b.Property<int>("RoleEnum");

                    b.Property<DateTime>("UnBlockDate");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserStatusType");

                    b.Property<int>("VerifiedBy");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("IpAddress");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Long")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserLocation");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserSubscriptionAreaAndLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaUnit");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Language");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptionAreaAndLanguages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PhoneCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Country");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("PhoneCodes");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PushNotifications.PushNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("PushNotificationActionType");

                    b.Property<int>("PushNotificationStatusType");

                    b.Property<int>("PushNotificationUserType");

                    b.Property<DateTime>("SendingDate");

                    b.Property<string>("Title");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("PushNotifications");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PushNotifications.PushNotificationTranslate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Language");

                    b.Property<int>("PushNotificationId");

                    b.Property<string>("Title");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("PushNotificationId");

                    b.ToTable("PushNotificationTranslate");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.GuestSaveFilterAnnouncementFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("FeatureType");

                    b.Property<int>("GuestSaveFilterId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestSaveFilterId");

                    b.ToTable("GuestSaveFilterAnnouncementFeatures");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.SaveFilterAnnouncementFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("FeatureType");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("SaveFilterId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("SaveFilterId");

                    b.ToTable("SaveFilterFeatures");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.GuestSaveFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("AnnouncementEstateType");

                    b.Property<int?>("AnnouncementRentType");

                    b.Property<int?>("AnnouncementResidentialType");

                    b.Property<int?>("AnnouncementType");

                    b.Property<int?>("BathroomCount");

                    b.Property<int?>("BedroomCount");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<int>("FilterCount");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("MaxArea");

                    b.Property<decimal?>("MinArea");

                    b.Property<decimal?>("PriceFrom");

                    b.Property<decimal?>("PriceTo");

                    b.Property<string>("SaveFilterName");

                    b.Property<string>("Search");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestSaveFilters");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.SaveFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int?>("AnnouncementEstateType");

                    b.Property<int?>("AnnouncementRentType");

                    b.Property<int?>("AnnouncementResidentialType");

                    b.Property<int?>("AnnouncementType");

                    b.Property<int?>("BathroomCount");

                    b.Property<int?>("BedroomCount");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description");

                    b.Property<int>("FilterCount");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("MaxArea");

                    b.Property<decimal?>("MinArea");

                    b.Property<decimal?>("PriceFrom");

                    b.Property<decimal?>("PriceTo");

                    b.Property<string>("SaveFilterName");

                    b.Property<string>("Search");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SaveFilters");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActivityDate");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int?>("GuestId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("GuestId")
                        .IsUnique()
                        .HasFilter("[GuestId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SupportConversations");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<long>("FileLength");

                    b.Property<int?>("GuestSenderId");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSeen");

                    b.Property<string>("MessageText");

                    b.Property<int>("SupportConversationId");

                    b.Property<int>("SupportMessageBodyType");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserSenderId");

                    b.HasKey("Id");

                    b.HasIndex("GuestSenderId");

                    b.HasIndex("SupportConversationId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Verified", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRegistered");

                    b.Property<bool>("IsVerified");

                    b.Property<string>("Phone");

                    b.Property<string>("PhoneCode");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("VerifiedBy");

                    b.Property<int>("VerifiedType");

                    b.HasKey("Id");

                    b.ToTable("Verifieds");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.ViewAnnouncements.ViewedAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int?>("GuestId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("GuestId");

                    b.HasIndex("UserId");

                    b.ToTable("ViewedAnnouncement");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementFeatures.AnnouncementFeature", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Features")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementReports.AnnouncementReport", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("AnnouncementReports")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Announcements.Announcement", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Announcements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Attachments.AnnouncementPhoto", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Photos")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Cities.City", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.SaveFilters.SaveFilter", "SaveFilter")
                        .WithMany()
                        .HasForeignKey("SaveFilterId");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Conversation", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "AnnouncementCreator")
                        .WithMany("CreatedConversations")
                        .HasForeignKey("AnnouncementCreatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Conversations")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "Questioner")
                        .WithMany("QuestionedConversations")
                        .HasForeignKey("QuestionerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Message", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Conversations.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.DeviceToken", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.Favourite", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Favorites")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.GuestFavourite", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("GuestFavourites")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("GuestFavourites")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscription", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("Subscriptions")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscriptionAreaAndLanguage", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithOne("GuestSubscriptionAreaAndLanguage")
                        .HasForeignKey("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscriptionAreaAndLanguage", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Notifications.NotificationTranslate", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Notifications.Notification", "Notification")
                        .WithMany("NotificationTranslate")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PersonNotifications.PersonNotification", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Notifications.Notification", "Notification")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.PushNotifications.PushNotification", "PushNotification")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("PushNotificationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Password", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Passwords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Subscription", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.User", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Cities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserLocation", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithOne("UserLocation")
                        .HasForeignKey("Baitkm.DAL.Entities.Persons.UserLocation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserSubscriptionAreaAndLanguage", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PushNotifications.PushNotificationTranslate", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.PushNotifications.PushNotification", "PushNotification")
                        .WithMany("PushNotificationTranslates")
                        .HasForeignKey("PushNotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.GuestSaveFilterAnnouncementFeature", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.SaveFilters.GuestSaveFilter", "GuestSaveFilter")
                        .WithMany("Features")
                        .HasForeignKey("GuestSaveFilterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.SaveFilterAnnouncementFeature", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.SaveFilters.SaveFilter", "SaveFilter")
                        .WithMany("Features")
                        .HasForeignKey("SaveFilterId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.GuestSaveFilter", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("GuestSaveFilters")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.SaveFilter", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("SaveFilters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Statistic", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Statistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportConversation", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "Admin")
                        .WithMany("SupportConversations")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithOne("SupportConversation")
                        .HasForeignKey("Baitkm.DAL.Entities.Supports.SupportConversation", "GuestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithOne("SupportConversation")
                        .HasForeignKey("Baitkm.DAL.Entities.Supports.SupportConversation", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportMessage", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "GuestSender")
                        .WithMany("SupportMessages")
                        .HasForeignKey("GuestSenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Supports.SupportConversation", "SupportConversation")
                        .WithMany("SupportMessages")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "UserSender")
                        .WithMany("SupportMessages")
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.ViewAnnouncements.ViewedAnnouncement", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("ViewedAnnouncements")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("ViewedAnnouncements")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("ViewedAnnouncements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
