// <auto-generated />
using System;
using Baitkm.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Baitkm.DAL.Migrations
{
    [DbContext(typeof(BaitkmDbContext))]
    [Migration("20201005153432_Add_Facts_Table")]
    partial class Add_Facts_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementFeatures.AnnouncementFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("FeatureType");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementReports.AnnouncementReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("ReportAnnouncementStatus");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("AnnouncementReports");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Announcements.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<DateTime>("AnnouncementApprovedDay");

                    b.Property<DateTime>("AnnouncementChangedDay");

                    b.Property<int>("AnnouncementEstateType");

                    b.Property<int?>("AnnouncementRentType");

                    b.Property<int?>("AnnouncementResidentialType");

                    b.Property<int>("AnnouncementStatus");

                    b.Property<DateTime>("AnnouncementStatusLastDay");

                    b.Property<int>("AnnouncementType");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("BalconyArea");

                    b.Property<string>("BasePhoto");

                    b.Property<int>("BathroomCount");

                    b.Property<int>("BedroomCount");

                    b.Property<int?>("BuildingAge");

                    b.Property<int>("CityId");

                    b.Property<int?>("CommercialType");

                    b.Property<int?>("ConstructionStatus");

                    b.Property<int>("CountryId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("CurrencyId");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("DescriptionArabian")
                        .HasMaxLength(2000);

                    b.Property<string>("DisctrictName")
                        .HasMaxLength(300);

                    b.Property<string>("District")
                        .HasMaxLength(300);

                    b.Property<int?>("FacadeType");

                    b.Property<bool>("FireSystem");

                    b.Property<int>("Floor");

                    b.Property<int?>("FurnishingStatus");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDraft");

                    b.Property<bool>("IsOtherPeriod");

                    b.Property<decimal?>("KitchenArea");

                    b.Property<bool>("LaborResidence");

                    b.Property<int?>("LandCategory");

                    b.Property<int?>("LandNumber");

                    b.Property<int?>("LandType");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("LaundryArea");

                    b.Property<decimal?>("LivingArea");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("MeterPrice");

                    b.Property<int?>("NumberOfAppartment");

                    b.Property<int?>("NumberOfFloors");

                    b.Property<int?>("NumberOfShop");

                    b.Property<int?>("NumberOfUnits");

                    b.Property<int?>("NumberOfVilla");

                    b.Property<int?>("NumberOfWareHouse");

                    b.Property<bool>("OfficeSpace");

                    b.Property<int?>("OwnerShip");

                    b.Property<int?>("PlanNumber");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int?>("SaleType");

                    b.Property<int?>("SittingCount");

                    b.Property<decimal?>("StreetWidth");

                    b.Property<string>("Title")
                        .HasMaxLength(1000);

                    b.Property<string>("TitleArabian")
                        .HasMaxLength(1000);

                    b.Property<bool>("TopAnnouncement");

                    b.Property<DateTime>("TopAnnouncementDayFrom");

                    b.Property<DateTime>("TopAnnouncementDayTo");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.Property<int>("ViewsCount");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Announcements.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<short>("Rat");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Attachments.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("AttachmentType");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("AnnouncementAttachments");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Cities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Cities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Configurations.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Language");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(3000);

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AnnouncementCreatorConversationIsDeleted");

                    b.Property<int>("AnnouncementCreatorId");

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("QuestionerConversationIsDeleted");

                    b.Property<int>("QuestionerId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementCreatorId");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("QuestionerId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConversationId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<long>("FileLength");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSeen");

                    b.Property<int>("MessageBodyType");

                    b.Property<string>("MessageText")
                        .HasMaxLength(1000);

                    b.Property<int>("ReciverId");

                    b.Property<bool>("ReciverMessageIsDeleted");

                    b.Property<int?>("ReplayMessageId");

                    b.Property<int>("SenderId");

                    b.Property<bool>("SenderMessageIsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("NumericCode");

                    b.Property<int>("RequestId");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(500);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("OsType");

                    b.Property<string>("Token")
                        .HasMaxLength(500);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("EmailText")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Fact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityType");

                    b.Property<int>("AnnouncementId");

                    b.Property<string>("AnnouncementPhoto")
                        .HasMaxLength(500);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGuest");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.ToTable("Facts");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourite");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.GuestFavourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestFavourites");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscribeAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestSubscribeAnnouncements");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("SubscriptionsType");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestSubscriptions");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscriptionAreaAndLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaUnit");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Language");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestId")
                        .IsUnique();

                    b.ToTable("GuestSubscriptionAreaAndLanguage");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.HomePageCoverImages.HomePageCoverImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsBase");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("HomePageCoverImages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("NotificationType");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Notifications.NotificationTranslate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Language");

                    b.Property<int>("NotificationId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationTranslate");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PersonNotifications.PersonNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int?>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSeen");

                    b.Property<int?>("NotificationId");

                    b.Property<int?>("PushNotificationId");

                    b.Property<int?>("SenderId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("GuestId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("PushNotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonNotifications");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("CurrencyId");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("OsType");

                    b.Property<string>("Token")
                        .HasMaxLength(500);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("LoginProvider");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("UniqueIdentifier")
                        .HasMaxLength(500);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Passwords");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("SubscriptionsType");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("CurrencyId");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("ForgotKey")
                        .HasMaxLength(100);

                    b.Property<int>("ForgotPasswordVerified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsBanned");

                    b.Property<bool>("IsBlocked");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocal");

                    b.Property<int>("OsType");

                    b.Property<string>("Phone")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(10);

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(1000);

                    b.Property<int>("RoleEnum");

                    b.Property<DateTime>("UnBlockDate");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserStatusType");

                    b.Property<int>("VerifiedBy");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Long")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserLocations");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserSubscriptionAreaAndLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaUnit");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Language");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSubscriptionAreaAndLanguages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PhoneCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Country");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("PhoneCodes");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PushNotifications.PushNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("PushNotificationActionType");

                    b.Property<int>("PushNotificationStatusType");

                    b.Property<int?>("PushNotificationUserType");

                    b.Property<DateTime>("SendingDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("PushNotifications");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PushNotifications.PushNotificationTranslate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Language");

                    b.Property<int>("PushNotificationId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("PushNotificationId");

                    b.ToTable("PushNotificationTranslate");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("CurrencyId");

                    b.Property<decimal>("CurrentRate")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.GuestSaveFilterAnnouncementFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("FeatureType");

                    b.Property<int>("GuestSaveFilterId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestSaveFilterId");

                    b.ToTable("GuestSaveFilterAnnouncementFeatures");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.SaveFilterAnnouncementFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int>("FeatureType");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("SaveFilterId");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("SaveFilterId");

                    b.ToTable("SaveFilterFeatures");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.GuestSaveFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<int?>("AnnouncementEstateType");

                    b.Property<int?>("AnnouncementRentType");

                    b.Property<int?>("AnnouncementResidentialType");

                    b.Property<int?>("AnnouncementType");

                    b.Property<int?>("BathroomCount");

                    b.Property<int?>("BedroomCount");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<int>("FilterCount");

                    b.Property<int>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("MaxArea");

                    b.Property<decimal?>("MinArea");

                    b.Property<decimal?>("PriceFrom");

                    b.Property<decimal?>("PriceTo");

                    b.Property<string>("SaveFilterName")
                        .HasMaxLength(100);

                    b.Property<string>("Search")
                        .HasMaxLength(100);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("GuestSaveFilters");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.SaveFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnnouncementEstateType");

                    b.Property<int?>("AnnouncementRentType");

                    b.Property<int?>("AnnouncementResidentialType");

                    b.Property<int?>("AnnouncementType");

                    b.Property<int?>("BathroomCount");

                    b.Property<int?>("BedroomCount");

                    b.Property<int?>("BuildingAge");

                    b.Property<int?>("CityId");

                    b.Property<int?>("CommercialType");

                    b.Property<int?>("ConstructionStatus");

                    b.Property<int?>("CountryId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<int?>("FacadeType");

                    b.Property<int>("FilterCount");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int?>("LandCategory");

                    b.Property<int?>("LandType");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal?>("MaxArea");

                    b.Property<decimal?>("MaxMeterPrice");

                    b.Property<decimal?>("MinArea");

                    b.Property<decimal?>("MinMeterPrice");

                    b.Property<int?>("OwnerShip");

                    b.Property<decimal?>("PriceFrom");

                    b.Property<decimal?>("PriceTo");

                    b.Property<int?>("SaleType");

                    b.Property<string>("SaveFilterName")
                        .HasMaxLength(100);

                    b.Property<string>("Search")
                        .HasMaxLength(100);

                    b.Property<int?>("SittingCount");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique()
                        .HasFilter("[CityId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("SaveFilters");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActivityDate");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int?>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("GuestId")
                        .IsUnique()
                        .HasFilter("[GuestId] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SupportConversations");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<long>("FileLength");

                    b.Property<int?>("GuestSenderId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSeen");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int?>("ReplayMessageId");

                    b.Property<int>("SupportConversationId");

                    b.Property<int>("SupportMessageBodyType");

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserSenderId");

                    b.HasKey("Id");

                    b.HasIndex("GuestSenderId");

                    b.HasIndex("SupportConversationId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.UserSubscribeAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscribeAnnouncements");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Verified", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(50);

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRegistered");

                    b.Property<bool>("IsVerified");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneCode")
                        .HasMaxLength(50);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int>("VerifiedBy");

                    b.Property<int>("VerifiedType");

                    b.HasKey("Id");

                    b.ToTable("Verifieds");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.ViewAnnouncements.ViewedAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnouncementId");

                    b.Property<int>("CreatedBy");

                    b.Property<DateTime>("CreatedDt");

                    b.Property<int?>("GuestId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("UpdatedBy");

                    b.Property<DateTime>("UpdatedDt");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("GuestId");

                    b.HasIndex("UserId");

                    b.ToTable("ViewedAnnouncement");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementFeatures.AnnouncementFeature", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Features")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.AnnouncementReports.AnnouncementReport", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("AnnouncementReports")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("AnnouncementReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Announcements.Announcement", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Announcements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Announcements.Rating", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Ratings")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Attachments.Attachment", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Photos")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Cities.City", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Cities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Conversation", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "AnnouncementCreator")
                        .WithMany("CreatedConversations")
                        .HasForeignKey("AnnouncementCreatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Conversations")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "Questioner")
                        .WithMany("QuestionedConversations")
                        .HasForeignKey("QuestionerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Conversations.Message", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Conversations.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.DeviceToken", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Fact", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Facts")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.Favourite", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("Favorites")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Favourites.GuestFavourite", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("GuestFavourites")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("GuestFavourites")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscribeAnnouncement", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("GuestSubscribeAnnouncements")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("GuestSubscribeAnnouncements")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscription", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("Subscriptions")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscriptionAreaAndLanguage", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithOne("GuestSubscriptionAreaAndLanguage")
                        .HasForeignKey("Baitkm.DAL.Entities.GuestSubscriptions.GuestSubscriptionAreaAndLanguage", "GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Notifications.NotificationTranslate", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Notifications.Notification", "Notification")
                        .WithMany("NotificationTranslate")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PersonNotifications.PersonNotification", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("AnnouncementId");

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("GuestId");

                    b.HasOne("Baitkm.DAL.Entities.Notifications.Notification", "Notification")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("NotificationId");

                    b.HasOne("Baitkm.DAL.Entities.PushNotifications.PushNotification", "PushNotification")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("PushNotificationId");

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("PersonNotifications")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Password", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Passwords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.Subscription", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.User", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Cities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserLocation", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithOne("UserLocation")
                        .HasForeignKey("Baitkm.DAL.Entities.Persons.UserLocation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Persons.UserSubscriptionAreaAndLanguage", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithOne("UserSubscriptionAreaAndLanguage")
                        .HasForeignKey("Baitkm.DAL.Entities.Persons.UserSubscriptionAreaAndLanguage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.PushNotifications.PushNotificationTranslate", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.PushNotifications.PushNotification", "PushNotification")
                        .WithMany("PushNotificationTranslates")
                        .HasForeignKey("PushNotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.GuestSaveFilterAnnouncementFeature", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.SaveFilters.GuestSaveFilter", "GuestSaveFilter")
                        .WithMany("Features")
                        .HasForeignKey("GuestSaveFilterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilterAnnouncementFeatures.SaveFilterAnnouncementFeature", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.SaveFilters.SaveFilter", "SaveFilter")
                        .WithMany("Features")
                        .HasForeignKey("SaveFilterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.GuestSaveFilter", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("GuestSaveFilters")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.SaveFilters.SaveFilter", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Cities.City")
                        .WithOne("SaveFilter")
                        .HasForeignKey("Baitkm.DAL.Entities.SaveFilters.SaveFilter", "CityId");

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("SaveFilters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Statistic", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("Statistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportConversation", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "Admin")
                        .WithMany("SupportConversations")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithOne("SupportConversation")
                        .HasForeignKey("Baitkm.DAL.Entities.Supports.SupportConversation", "GuestId");

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithOne("SupportConversation")
                        .HasForeignKey("Baitkm.DAL.Entities.Supports.SupportConversation", "UserId");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.Supports.SupportMessage", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "GuestSender")
                        .WithMany("SupportMessages")
                        .HasForeignKey("GuestSenderId");

                    b.HasOne("Baitkm.DAL.Entities.Supports.SupportConversation", "SupportConversation")
                        .WithMany("SupportMessages")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "UserSender")
                        .WithMany("SupportMessages")
                        .HasForeignKey("UserSenderId");
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.UserSubscribeAnnouncement", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("UserSubscribeAnnouncements")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("UserSubscribeAnnouncements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Baitkm.DAL.Entities.ViewAnnouncements.ViewedAnnouncement", b =>
                {
                    b.HasOne("Baitkm.DAL.Entities.Announcements.Announcement", "Announcement")
                        .WithMany("ViewedAnnouncements")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Baitkm.DAL.Entities.Persons.Guest", "Guest")
                        .WithMany("ViewedAnnouncements")
                        .HasForeignKey("GuestId");

                    b.HasOne("Baitkm.DAL.Entities.Persons.User", "User")
                        .WithMany("ViewedAnnouncements")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
